User.create!(:email => "test@gmail.com", :password => "123456")
Team.create!(:name => "团队一", :user_id => "1" )
Project.create!(:title => "项目一", :team_id => "1", :user_id => "1")
Todo.create!(:title => "任务一", :description => "任务一描述", :team_id => "1", :user_id => "1", :project_id => "1")
Review.create!(:content => "评论", :todo_id => "1", :team_id => "1", :user_id => "1", :project_id => "1")
